# Generated by Django 2.1.5 on 2025-03-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0007_page_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
